// tauri-app-preact/src/app.tsx
import { Logo } from './logo'

import {useState} from 'preact/hooks'

export const App = () => {
  const [count, setCount] = useState(0)
  return (
    <>
      <Logo />
      <p>Hello Vite + Preact!</p>
      <p>
          <button type="button" onClick={() => setCount((count) => count + 1)}>
            count is: {count}
          </button>
        </p>
      <p>
        <a
          class="link"
          href="https://preactjs.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn Preact
        </a>
      </p>
    </>
  )
}

// tauri-app-solid/src/App.tsx
import type { Component } from 'solid-js';

import styles from './App.module.css';

import CardEntry from './components/CardEntry'

const App: Component = () => {
  return (
    <div class={styles.App}>
      <header class={styles.header}>
        <a
          class={styles.link}
          href="https://github.com/solidjs/solid"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn Solid
        </a>
        <CardEntry />
      </header>
    </div>
  );
};

export default App;
